"""Add users table

Revision ID: 0757e672bd5e
Revises: cb977b260575
Create Date: 2026-02-11 20:46:01.846520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0757e672bd5e'
down_revision: Union[str, Sequence[str], None] = 'cb977b260575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('budget_categories', 'budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'village_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_village_year', 'budgets', ['village_id', 'year'])
    op.alter_column('expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_village_year', 'budgets', type_='unique')
    op.alter_column('budgets', 'village_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('budget_categories', 'budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
