"""add_village_id_to_users

Revision ID: 52279cc470c6
Revises: 0757e672bd5e
Create Date: 2026-02-11 23:21:37.867239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52279cc470c6'
down_revision: Union[str, Sequence[str], None] = '0757e672bd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('village_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'villages', ['village_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'village_id')
    # ### end Alembic commands ###
